# Generated by Django 6.0.5 on 2026-05-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('source', models.CharField(blank=True, help_text='Ex: upload manual, API XPTO, integracao SAP...', max_length=120, verbose_name='Origem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafy_datasets', to='accounts.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=40, verbose_name='Codigo')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('financial', 'Financeiro'), ('safety', 'Seguranca'), ('quality', 'Qualidade'), ('operations', 'Operacoes'), ('other', 'Outro')], default='performance', max_length=30, verbose_name='Categoria')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unidade')),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Meta')),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['code'],
                'unique_together': {('client', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['code'],
                'unique_together': {('client', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Valor')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Observacao')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='datafy.indicator')),
            ],
            options={
                'verbose_name': 'Valor de indicador',
                'verbose_name_plural': 'Valores de indicadores',
                'ordering': ['-period'],
                'unique_together': {('indicator', 'period')},
            },
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=80, verbose_name='Referencia')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberto'), ('in_progress', 'Em andamento'), ('done', 'Concluido'), ('blocked', 'Bloqueado'), ('cancelled', 'Cancelado')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Quantidade')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor')),
                ('event_date', models.DateField(db_index=True, verbose_name='Data do evento')),
                ('owner', models.CharField(blank=True, max_length=120, verbose_name='Responsavel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='accounts.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_entries', to='datafy.project')),
            ],
            options={
                'verbose_name': 'Registro Datafy',
                'verbose_name_plural': 'Registros Datafy',
                'ordering': ['-event_date', '-id'],
                'indexes': [models.Index(fields=['client', 'event_date'], name='datafy_data_client__2d004c_idx'), models.Index(fields=['status', 'event_date'], name='datafy_data_status_040da1_idx')],
            },
        ),
    ]
