# Generated by Django 5.0.6 on 2026-09-15 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISListenerState',
            fields=[
                ('provider', models.CharField(default='aisstream', max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('idle', 'Waiting for active vessels'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('reconnecting', 'Reconnecting'), ('configuration_error', 'Configuration required')], default='stopped', max_length=24)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('active_vessel_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'MMSI must contain exactly nine digits.')])),
                ('name', models.CharField(blank=True, max_length=120)),
                ('imo', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9]{7}$', 'IMO must contain exactly seven digits.')])),
                ('vessel_type', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('eta', models.JSONField(blank=True, default=dict, help_text='Declared AIS month/day/hour/minute; no year is inferred.')),
                ('draught', models.FloatField(blank=True, null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_sog', models.FloatField(blank=True, null=True)),
                ('last_cog', models.FloatField(blank=True, null=True)),
                ('last_heading', models.FloatField(blank=True, null=True)),
                ('last_navigational_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_static_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'mmsi'],
            },
        ),
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('sog', models.FloatField(blank=True, null=True)),
                ('cog', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('navigational_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(default='AIS', editable=False, max_length=8)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.CheckConstraint(check=models.Q(('mmsi__regex', '^[0-9]{9}$')), name='vessel_mmsi_nine_digits'),
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.CheckConstraint(check=models.Q(('last_latitude__isnull', True), ('last_latitude__range', (-90, 90)), _connector='OR'), name='vessel_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.CheckConstraint(check=models.Q(('last_longitude__isnull', True), ('last_longitude__range', (-180, 180)), _connector='OR'), name='vessel_longitude_range'),
        ),
        migrations.AddField(
            model_name='vesselposition',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='vessels.vessel'),
        ),
        migrations.AddIndex(
            model_name='vesselposition',
            index=models.Index(fields=['vessel', 'timestamp'], name='vessel_position_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='vesselposition',
            constraint=models.UniqueConstraint(fields=('vessel', 'timestamp'), name='vessel_position_unique_time'),
        ),
        migrations.AddConstraint(
            model_name='vesselposition',
            constraint=models.CheckConstraint(check=models.Q(('source', 'AIS')), name='vessel_position_ais_only'),
        ),
        migrations.AddConstraint(
            model_name='vesselposition',
            constraint=models.CheckConstraint(check=models.Q(('latitude__range', (-90, 90))), name='vessel_position_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='vesselposition',
            constraint=models.CheckConstraint(check=models.Q(('longitude__range', (-180, 180))), name='vessel_position_lon_range'),
        ),
    ]
