# Generated by Django 5.0.6 on 2026-09-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='last_provider',
            field=models.CharField(blank=True, help_text='Channel that delivered the current position; the observation itself is always AIS.', max_length=32),
        ),
        migrations.AddField(
            model_name='vesselposition',
            name='provider',
            field=models.CharField(db_index=True, default='aisstream', editable=False, max_length=32),
        ),
    ]
