# Generated by Django 6.0.5 on 2026-05-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.CharField(blank=True, max_length=120)),
                ('result', models.CharField(choices=[('success', 'Sucesso'), ('partial', 'Parcial'), ('failed', 'Falha')], max_length=20)),
                ('documents_created', models.IntegerField(default=0)),
                ('documents_updated', models.IntegerField(default=0)),
                ('documents_errored', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eclic_syncs', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Log de sincronizacao',
                'verbose_name_plural': 'Logs de sincronizacao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=80, verbose_name='ID externo (ECLIC)')),
                ('code', models.CharField(db_index=True, max_length=80, verbose_name='Codigo')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Categoria')),
                ('document_type', models.CharField(blank=True, max_length=80, verbose_name='Tipo')),
                ('revision', models.CharField(blank=True, max_length=20, verbose_name='Revisao')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisao'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('obsolete', 'Obsoleto')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('url', models.URLField(blank=True, verbose_name='Link no ECLIC')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Data de emissao')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima sincronizacao')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='Payload bruto')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eclic_documents', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Documento ECLIC',
                'verbose_name_plural': 'Documentos ECLIC',
                'ordering': ['-issued_at', 'code'],
                'indexes': [models.Index(fields=['client', 'category'], name='eclic_docum_client__557be7_idx'), models.Index(fields=['status'], name='eclic_docum_status_c581d8_idx')],
                'unique_together': {('client', 'external_id')},
            },
        ),
    ]
