# Generated by Django 6.0.5 on 2026-05-23 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P6CurveImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('progress_sheet', models.CharField(default='Progress PMS (%)', max_length=120)),
                ('curve_sheet', models.CharField(default='DB (%)', max_length=120)),
                ('progress_row_count', models.PositiveIntegerField(default=0)),
                ('curve_point_count', models.PositiveIntegerField(default=0)),
                ('executive_row_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p6_curve_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importacao de curva P6',
                'verbose_name_plural': 'Importacoes de curvas P6',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='P6CurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('period', models.DateField(db_index=True)),
                ('planned_pct', models.FloatField(default=0)),
                ('actual_pct', models.FloatField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curve_points', to='core.p6curveimport')),
            ],
            options={
                'verbose_name': 'Ponto de curva P6',
                'verbose_name_plural': 'Pontos de curva P6',
                'ordering': ['sequence', 'period'],
            },
        ),
        migrations.CreateModel(
            name='P6ProgressRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('level', models.PositiveSmallIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('weight_pct', models.FloatField(default=0)),
                ('baseline_pct', models.FloatField(default=0)),
                ('planned_pct', models.FloatField(default=0)),
                ('actual_pct', models.FloatField(default=0)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='core.p6curveimport')),
            ],
            options={
                'verbose_name': 'Linha PMS P6',
                'verbose_name_plural': 'Linhas PMS P6',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='p6curveimport',
            index=models.Index(fields=['is_active', '-created_at'], name='core_p6curv_is_acti_a32d02_idx'),
        ),
        migrations.AddIndex(
            model_name='p6curveimport',
            index=models.Index(fields=['file_hash'], name='core_p6curv_file_ha_341297_idx'),
        ),
        migrations.AddIndex(
            model_name='p6curvepoint',
            index=models.Index(fields=['import_batch', 'period'], name='core_p6curv_import__ce38da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='p6curvepoint',
            unique_together={('import_batch', 'period')},
        ),
        migrations.AddIndex(
            model_name='p6progressrow',
            index=models.Index(fields=['import_batch', 'level'], name='core_p6prog_import__e70d79_idx'),
        ),
        migrations.AddIndex(
            model_name='p6progressrow',
            index=models.Index(fields=['import_batch', 'row_number'], name='core_p6prog_import__633a5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='p6progressrow',
            unique_together={('import_batch', 'row_number')},
        ),
    ]
