# Generated by Django 6.0.5 on 2026-05-23 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_p6curveimport_p6curvepoint_p6progressrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatafySupplySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_database', models.CharField(default='DATAFY', max_length=120)),
                ('source_host', models.CharField(blank=True, max_length=120)),
                ('filters_hash', models.CharField(db_index=True, max_length=64)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('total_materials', models.PositiveIntegerField(default=0)),
                ('total_drawings', models.PositiveIntegerField(default=0)),
                ('material_rows', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('refreshed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafy_supply_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot de suprimentos DATAFY',
                'verbose_name_plural': 'Snapshots de suprimentos DATAFY',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'filters_hash', '-created_at'], name='core_datafy_is_acti_ddd809_idx'), models.Index(fields=['filters_hash', '-created_at'], name='core_datafy_filters_f66df9_idx')],
            },
        ),
    ]
