# Generated by Django 6.0.5 on 2026-05-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datafysupplysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='P6ManagementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('monthly_point_count', models.PositiveIntegerField(default=0)),
                ('area_count', models.PositiveIntegerField(default=0)),
                ('source_sheet', models.CharField(default='DB BLPMSACT', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_snapshot', to='core.p6curveimport')),
            ],
            options={
                'verbose_name': 'Snapshot gerencial P6',
                'verbose_name_plural': 'Snapshots gerenciais P6',
                'ordering': ['-created_at'],
            },
        ),
    ]
