# Generated by Django 6.0.5 on 2026-05-23 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_p6managementsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringStatusImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('summary_sheet', models.CharField(default='Sheet2', max_length=120)),
                ('detail_sheet', models.CharField(default='Sheet1', max_length=120)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('discipline_count', models.PositiveIntegerField(default=0)),
                ('summary_row_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_status_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importacao DED engenharia',
                'verbose_name_plural': 'Importacoes DED engenharia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringDocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('document_number', models.CharField(db_index=True, max_length=180)),
                ('title', models.CharField(blank=True, max_length=600)),
                ('discipline', models.CharField(db_index=True, max_length=160)),
                ('revision', models.CharField(blank=True, db_index=True, max_length=40)),
                ('revision_family', models.CharField(blank=True, db_index=True, max_length=8)),
                ('revision_number', models.PositiveSmallIntegerField(default=0)),
                ('doc_status', models.CharField(blank=True, db_index=True, max_length=120)),
                ('doc_status_group', models.CharField(blank=True, db_index=True, max_length=40)),
                ('afc_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('document_status', models.CharField(blank=True, db_index=True, max_length=120)),
                ('workflow_start', models.DateField(blank=True, null=True)),
                ('workflow_end', models.DateField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, db_index=True, max_length=160)),
                ('issue_status', models.CharField(blank=True, db_index=True, max_length=180)),
                ('fabrication_ref', models.CharField(blank=True, max_length=180)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.engineeringstatusimport')),
            ],
            options={
                'verbose_name': 'Documento DED engenharia',
                'verbose_name_plural': 'Documentos DED engenharia',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringDisciplineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('discipline', models.CharField(db_index=True, max_length=160)),
                ('not_issued', models.PositiveIntegerField(default=0)),
                ('ifr', models.PositiveIntegerField(default=0)),
                ('ifa', models.PositiveIntegerField(default=0)),
                ('afc_code1', models.PositiveIntegerField(default=0)),
                ('afc_code3', models.PositiveIntegerField(default=0)),
                ('mabu_under_review', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_summaries', to='core.engineeringstatusimport')),
            ],
            options={
                'verbose_name': 'Resumo DED por disciplina',
                'verbose_name_plural': 'Resumos DED por disciplina',
                'ordering': ['row_number', 'discipline'],
            },
        ),
        migrations.AddIndex(
            model_name='engineeringstatusimport',
            index=models.Index(fields=['is_active', '-created_at'], name='core_engine_is_acti_276a52_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringstatusimport',
            index=models.Index(fields=['file_hash'], name='core_engine_file_ha_fb4425_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringdocumentstatus',
            index=models.Index(fields=['import_batch', 'discipline'], name='core_engine_import__e1b388_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringdocumentstatus',
            index=models.Index(fields=['import_batch', 'revision_family'], name='core_engine_import__9daaf9_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringdocumentstatus',
            index=models.Index(fields=['import_batch', 'doc_status_group'], name='core_engine_import__7cf733_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringdocumentstatus',
            index=models.Index(fields=['import_batch', 'document_status'], name='core_engine_import__e42b78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='engineeringdocumentstatus',
            unique_together={('import_batch', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='engineeringdisciplinestatus',
            index=models.Index(fields=['import_batch', 'discipline'], name='core_engine_import__543cfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='engineeringdisciplinestatus',
            unique_together={('import_batch', 'row_number')},
        ),
    ]
