# Generated by Codex on 2026-05-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_engineeringstatusimport_engineeringdocumentstatus_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineeringMonitorImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("detail_sheet", models.CharField(default="Sheet1", max_length=120)),
                ("document_count", models.PositiveIntegerField(default=0)),
                ("monitored_document_count", models.PositiveIntegerField(default=0)),
                ("discipline_count", models.PositiveIntegerField(default=0)),
                ("excluded_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engineering_monitor_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Importacao monitor engenharia",
                "verbose_name_plural": "Importacoes monitor engenharia",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="engineeringmonitorimport",
            index=models.Index(fields=["is_active", "-created_at"], name="core_engine_is_acti_5ce6d8_idx"),
        ),
        migrations.AddIndex(
            model_name="engineeringmonitorimport",
            index=models.Index(fields=["file_hash"], name="core_engine_file_ha_a29c06_idx"),
        ),
    ]
