# Generated by Django 5.0.6 on 2026-09-24 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
        ('core', '0008_rundownimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.CharField(default='BN-EPC1', editable=False, max_length=40)),
                ('section', models.CharField(max_length=8)),
                ('author_name', models.CharField(max_length=300)),
                ('note_date', models.DateField()),
                ('body', models.TextField(max_length=4000)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('information_only', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('resolved', 'Sanado'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SectionNoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(max_length=12)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.sectionnote')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='sectionnote',
            index=models.Index(fields=['project', 'client', 'section'], name='core_sectio_project_878e26_idx'),
        ),
    ]
