# Generated by Django 5.0.6 on 2026-09-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_section_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionnote',
            name='panel',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
